name 'andschwa-latex'
version '0.0.1'
source 'git://github.com/andschwa/puppet-latex.git'
author 'Andrew Schwartzmeyer'
license 'MIT License'
summary 'Install TeX Live'
description 'Installs TeX Live for Ubuntu'
project_page 'https://github.com/andschwa/puppet-latex'

dependency 'puppetlabs/apt', '>= 1.4.0'
